version: '2'
services:
    mariadb:
#        image: xiaozhuai/mariadb-alpine:latest
        build: .
        ports:
            - 13306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./data:/data
