version: '2'
services:
    mariadb:
#        image: xiaozhuai/mariadb-alpine:latest
        build: .
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - ./data:/data
